name: Mapr Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Nuke Restore
      run: dotnet restore ./build/
    
    - name: Nuke Build
      run: /home/runner/.dotnet/dotnet /home/runner/.nuget/packages/gitversion.tool/5.5.1/tools/netcoreapp3.1/any/gitversion.dll /home/runner/work/mapr
