name: Mapr Build & Nuget Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Nuke
      run: ./build.sh publish --nuget-api-key $NUGET_AUTH_TOKEN
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
